packaging_format = 2

id = "ssbroom"
name = "Scuttlebutt Room"
description.en = "Secure Scuttlebutt room server"
description.fr = "Serveur de salon Scuttlebutt sécurisé"

version = "2.0.6~ynh6"

maintainers = ["Max Fowler"]

[upstream]
license = "MIT"
demo = "https://hermies.club/"
admindoc = "https://github.com/ssb-ngi-pointer/go-ssb-room/blob/master/README.md"
userdoc = "https://github.com/ssb-ngi-pointer/go-ssb-room/blob/master/README.md"
code = "https://github.com/ssb-ngi-pointer/go-ssb-room"

[integration]
yunohost = ">= 11.2"
architectures = ["amd64", "arm64", "armhf"]
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"
    full_domain = true

    [install.init_main_permission]
    help.en = "SSB rooms work best when the app is in visitors mode."
    help.fr = "Les salons SSB fonctionnent mieux lorsque l'application est en mode visiteurs."
    type = "group"
    default = "visitors"

    [install.ssb_admin_id]
    ask.en = "SSB ID of first admin of the room"
    ask.fr = "ID SSB du premier administrateur du salon"
    help.en = "This ssb_id is used as the username for the first admin of the room. Create an SSB account or use your already existing ssb account, and use your ssb public key as the room admin id."
    type = "string"
    example = "@5Pt3dKy2HTJ0mWuS78oIiklIX0gBz6BTfEnXsbvke9c=.ed25519"

    [install.password]
    help.en = "Use this password to log into the admin interface for the SSB room."
    help.fr = "Utilisez ce mot de passe pour vous connecter à l'interface d'administration de la salle SSB."
    type = "password"

[resources]
        [resources.sources.main]
        url = "https://github.com/ssbc/go-ssb-room/archive/refs/tags/v2.0.6.tar.gz"
        sha256 = "2ee764972ace3560b341aa3ed4c4e62e9a332426ba2b607ecf3e5e4578ac36c4"
        autoupdate.strategy = "latest_github_tag"

    [resources.ports]
    main.default = 8899
    ssb.default = 8008
    ssb.exposed = "TCP"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "expect"
